### 휴가기안 작성
POST http://localhost:8031/approval/dayOffApply
Accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzA3ODE1MzIzNjk2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDIiLCJ1c2VyUmFuayI6IuqzvOyepSIsInVzZXJOYW1lIjoiMjAwMzAyMDAyIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoyLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fV0sImV4cCI6MTcwNzgzMzMyMywidXNlcklkIjoiMjAwMzAyMDAyIiwidXNlckNvZGUiOjIsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSJ9.Sa_Qm_KQA5yOxdYhdvBEKSiRI8WQenUhrs_Pa8rafTg


--WebAppBoundary
Content-Disposition: form-data; name="offApplyTitle"

휴가신청서
--WebAppBoundary
Content-Disposition: form-data; name="offStart"

2024-03-01
--WebAppBoundary
Content-Disposition: form-data; name="offEnd"

2024-03-04
--WebAppBoundary
Content-Disposition: form-data; name="offDay"

4
--WebAppBoundary
Content-Disposition: form-data; name="offReason"

연차
--WebAppBoundary
Content-Disposition: form-data; name="offState"

대기
--WebAppBoundary
Content-Disposition: form-data; name="rfUser"

3
--WebAppBoundary
Content-Disposition: form-data; name="lineUser"

1
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="3333.png"

< ./3333.png
--WebAppBoundary--





### 출장기안 작성
POST http://localhost:8031/approval/businessTrip
Accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzA3NTUxMzIwOTI4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc1NjkzMjAsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.G7cGX_x6p7lUfcuHvHcmqHcJow7jFzmVMDn9E_ykrzo

--WebAppBoundary
Content-Disposition: form-data; name="btPhone"

01022222222
--WebAppBoundary
Content-Disposition: form-data; name="btStart"

2024-02-15
--WebAppBoundary
Content-Disposition: form-data; name="btFinish"

2024-02-18
--WebAppBoundary
Content-Disposition: form-data; name="btPlace"

강원도 삼척시 삼척동
--WebAppBoundary
Content-Disposition: form-data; name="btContent"

수리
--WebAppBoundary
Content-Disposition: form-data; name="btTitle"

출장신청서
--WebAppBoundary
Content-Disposition: form-data; name="rfUser"

2,3
--WebAppBoundary
Content-Disposition: form-data; name="lineUser"

21,22,19
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="3333.png"

< ./3333.png
--WebAppBoundary--





### 교육기안 작성
POST http://localhost:8031/approval/education
Accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzA3MzU3NTUxNjYyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDczNzU1NTEsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.8lsYSGEG1ZOqndHd_6LO2TQ0tYmN9LALDNBpXVR5kjI

--WebAppBoundary
Content-Disposition: form-data; name="eduTitle"

교육기안 신청서
--WebAppBoundary
Content-Disposition: form-data; name="eduName"

장재영
--WebAppBoundary
Content-Disposition: form-data; name="eduStart"

2024-06-01
--WebAppBoundary
Content-Disposition: form-data; name="eduFinish"

2024-12-01
--WebAppBoundary
Content-Disposition: form-data; name="eduInstitution"

장재영 사람 만들기 교육기관
--WebAppBoundary
Content-Disposition: form-data; name="eduPrice"

75000000
--WebAppBoundary
Content-Disposition: form-data; name="eduContent"

사람이 되기 위해 교육을 받고 싶습니다.
--WebAppBoundary
Content-Disposition: form-data; name="rfUser"

2,3
--WebAppBoundary
Content-Disposition: form-data; name="lineUser"

21,22,19
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="3333.png"

< ./3333.png
--WebAppBoundary--

### 일반기안 작성
POST http://localhost:8031/approval/generalDraft
Accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzA4NTAyNTQ5NTIwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDg1MjA1NDksInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.cY-VmpWteXqLjG0Z75MyfpKuklS0xfqW_nYHdiS2EY8

--WebAppBoundary
Content-Disposition: form-data; name="gdTitle"

교육기안 신청서
--WebAppBoundary
Content-Disposition: form-data; name="gdContent"

장재영
--WebAppBoundary
Content-Disposition: form-data; name="rfUser"

21,22
--WebAppBoundary
Content-Disposition: form-data; name="lineUser"

1
--WebAppBoundary
Content-Disposition: form-data; name="file" filename="apFileNameOrigin.png"

< ./3333.png
--WebAppBoundary--

### 기안한 문서 조회
GET http://localhost:8031/approval/document
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3ODkxMzM2OTQ0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc5MDkzMzYsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.lZQgz7W2Rc571SyCn-jwpHRrPcL8_zeW9lOo9Q42A2o

### 결재 대기 문서 조회
GET http://localhost:8031/approval/inboxApproval
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3OTA2MjUxMTA3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc5MjQyNTEsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ._s5rQwXCEwuA-LxtOuBehcWsiQtLjoE9NoE2yLjPVwc

### 결재하기
PUT http://localhost:8031/approval/approvement/82
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODE1MDQ3OTgwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDIiLCJ1c2VyUmFuayI6IuqzvOyepSIsInVzZXJOYW1lIjoiMjAwMzAyMDAyIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoyLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fV0sImV4cCI6MTcwNzgzMzA0NywidXNlcklkIjoiMjAwMzAyMDAyIiwidXNlckNvZGUiOjIsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSJ9.OEQJXbUCp_BSNGrGm_tVt6LDrtbI-TNzmU51VCinaTU

### 문서별 결재자
GET http://localhost:8031/approval/selectApprovalLine/142
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NTMyNzg1MzU5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDMiLCJ1c2VyUmFuayI6IuydtOyCrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAzIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjozLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fV0sImV4cCI6MTcwODU1MDc4NSwidXNlcklkIjoiMjAwMzAyMDAzIiwidXNlckNvZGUiOjMsImVtYWlsIjoiYXNkQGdtYWlsLmNvbSJ9.1cGBoTp4KA7dFMNqiN4EgvLcGI3hdpFlWhtSHK9yN6s

### 문서별 참조자
GET http://localhost:8031/approval/selectApprovalRf/142
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NTMyNzg1MzU5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDMiLCJ1c2VyUmFuayI6IuydtOyCrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAzIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjozLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fV0sImV4cCI6MTcwODU1MDc4NSwidXNlcklkIjoiMjAwMzAyMDAzIiwidXNlckNvZGUiOjMsImVtYWlsIjoiYXNkQGdtYWlsLmNvbSJ9.1cGBoTp4KA7dFMNqiN4EgvLcGI3hdpFlWhtSHK9yN6s

### 반려하기
PUT http://localhost:8031/approval/rejection/85
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODE1MzY3MDg3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4MzMzNjcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.bAZgL7T6XOxDiKmOyfDV1LntnoiNUIKaazJeypVb-LM

### 회수하기
PUT http://localhost:8031/approval/withdraw/84
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODE1MjA3MjI1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4MzMyMDcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.4EwHsbnfzFnVKCvquBDbIsRPoVECQnm4BsWrOOCbh8M

### 결재 진행 중인 문서 조회
GET http://localhost:8031/approval/approvalProgress
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4MDE1MDc1NTE2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDMiLCJ1c2VyUmFuayI6IuydtOyCrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAzIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjozLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fV0sImV4cCI6MTcwODAzMzA3NSwidXNlcklkIjoiMjAwMzAyMDAzIiwidXNlckNvZGUiOjMsImVtYWlsIjoiYXNkQGdtYWlsLmNvbSJ9.1T5SFfE0ZRG16VWScfeIdNPT0IjLtgqmW-q6Snlq8oU

### 결재 완료 문서 조회
GET http://localhost:8031/approval/approvalComplete
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODkxMzM2OTQ0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc5MDkzMzYsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.lZQgz7W2Rc571SyCn-jwpHRrPcL8_zeW9lOo9Q42A2o

### 반려 문서 조회
GET http://localhost:8031/approval/rejection
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODkxMzM2OTQ0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc5MDkzMzYsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.lZQgz7W2Rc571SyCn-jwpHRrPcL8_zeW9lOo9Q42A2o


### 회수 문서 조회
GET http://localhost:8031/approval/withdraw
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODkxMzM2OTQ0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc5MDkzMzYsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.lZQgz7W2Rc571SyCn-jwpHRrPcL8_zeW9lOo9Q42A2o

### 임시저장 문서 상세조회
GET http://localhost:8031/approval/selectTempDocumentDetail/89
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NTEzMDQzMzI4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDg1MzEwNDMsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.exib4zUTaD-hJH3l4IMmIShhmLRXYeO8vC06oaeeTIc


### 임시 휴가기안 작성
POST http://localhost:8031/approval/saveApprovalDayOff
Accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzA3ODE1MzY3MDg3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4MzMzNjcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.bAZgL7T6XOxDiKmOyfDV1LntnoiNUIKaazJeypVb-LM


--WebAppBoundary
Content-Disposition: form-data; name="offApplyTitle"

휴가신청서
--WebAppBoundary
Content-Disposition: form-data; name="offStart"

2024-03-01
--WebAppBoundary
Content-Disposition: form-data; name="offEnd"

2024-03-04
--WebAppBoundary
Content-Disposition: form-data; name="offDay"

4
--WebAppBoundary
Content-Disposition: form-data; name="offReason"

연차
--WebAppBoundary
Content-Disposition: form-data; name="offState"

대기
--WebAppBoundary




### 임시 출장기안 작성
POST http://localhost:8031/approval/saveApprovalBusinessTrip
Accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzA3ODE1MzY3MDg3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4MzMzNjcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.bAZgL7T6XOxDiKmOyfDV1LntnoiNUIKaazJeypVb-LM

--WebAppBoundary
Content-Disposition: form-data; name="btPhone"

01022222222
--WebAppBoundary
Content-Disposition: form-data; name="btStart"

2024-02-15
--WebAppBoundary
Content-Disposition: form-data; name="btFinish"

2024-02-18
--WebAppBoundary
Content-Disposition: form-data; name="btPlace"

강원도 삼척시 삼척동
--WebAppBoundary
Content-Disposition: form-data; name="btContent"

수리
--WebAppBoundary
Content-Disposition: form-data; name="btTitle"

출장신청서
--WebAppBoundary






### 임시 교육기안 작성
POST http://localhost:8031/approval/saveApprovalEducation
Accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzA3ODE1MzY3MDg3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4MzMzNjcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.bAZgL7T6XOxDiKmOyfDV1LntnoiNUIKaazJeypVb-LM

--WebAppBoundary
Content-Disposition: form-data; name="eduTitle"

교육기안 신청서
--WebAppBoundary
Content-Disposition: form-data; name="eduName"

장재영
--WebAppBoundary
Content-Disposition: form-data; name="eduStart"

2024-06-01
--WebAppBoundary
Content-Disposition: form-data; name="eduFinish"

2024-12-01
--WebAppBoundary
Content-Disposition: form-data; name="eduInstitution"

장재영 사람 만들기 교육기관
--WebAppBoundary
Content-Disposition: form-data; name="eduPrice"

75000000
--WebAppBoundary
Content-Disposition: form-data; name="eduContent"

사람이 되기 위해 교육을 받고 싶습니다.
--WebAppBoundary


### 임시 일반기안 작성
POST http://localhost:8031/approval/saveApprovalGeneral
Accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzA3ODE1MzY3MDg3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4MzMzNjcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.bAZgL7T6XOxDiKmOyfDV1LntnoiNUIKaazJeypVb-LM

--WebAppBoundary
Content-Disposition: form-data; name="gdTitle"

구매 품의서
--WebAppBoundary
Content-Disposition: form-data; name="gdContent"

볼펜 구매
개당 가격 : 2000
수량 : 4
합계 : 8000원
--WebAppBoundary

### 임시 기안한 문서 조회
GET http://localhost:8031/approval/tempSaveDocument
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3ODE1MzY3MDg3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4MzMzNjcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.bAZgL7T6XOxDiKmOyfDV1LntnoiNUIKaazJeypVb-LM


### 임시 기안한 문서 조회 후 기안작성
PUT http://localhost:8031/approval/insertBySelectTempDocument/87
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3ODE1MzY3MDg3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4MzMzNjcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.bAZgL7T6XOxDiKmOyfDV1LntnoiNUIKaazJeypVb-LM

--WebAppBoundary
Content-Disposition: form-data; name="btPhone"

01022222222
--WebAppBoundary
Content-Disposition: form-data; name="btStart"

2024-02-15
--WebAppBoundary
Content-Disposition: form-data; name="btFinish"

2024-02-18
--WebAppBoundary
Content-Disposition: form-data; name="btPlace"

강원도 삼척시 삼척동
--WebAppBoundary
Content-Disposition: form-data; name="btContent"

수리
--WebAppBoundary
Content-Disposition: form-data; name="btTitle"

출장신청서
--WebAppBoundary
Content-Disposition: form-data; name="rfUser"

2,3
--WebAppBoundary
Content-Disposition: form-data; name="lineUser"

21,22,19
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="3333.png"

< ./3333.png
--WebAppBoundary--
Content-Disposition: form-data; name="btPhone"

01022222222
--WebAppBoundary
Content-Disposition: form-data; name="btStart"

2024-02-15
--WebAppBoundary
Content-Disposition: form-data; name="btFinish"

2024-02-18
--WebAppBoundary
Content-Disposition: form-data; name="btPlace"

강원도 삼척시 삼척동
--WebAppBoundary
Content-Disposition: form-data; name="btContent"

수리
--WebAppBoundary
Content-Disposition: form-data; name="btTitle"

출장신청서
--WebAppBoundary
Content-Disposition: form-data; name="eduTitle"

교육기안 신청서
--WebAppBoundary
Content-Disposition: form-data; name="eduName"

장재영
--WebAppBoundary
Content-Disposition: form-data; name="eduStart"

2024-06-01
--WebAppBoundary
Content-Disposition: form-data; name="eduFinish"

2024-12-01
--WebAppBoundary
Content-Disposition: form-data; name="eduInstitution"

장재영 사람 만들기 교육기관
--WebAppBoundary
Content-Disposition: form-data; name="eduPrice"

75000000
--WebAppBoundary
Content-Disposition: form-data; name="eduContent"

사람이 되기 위해 교육을 받고 싶습니다.
--WebAppBoundary
Content-Disposition: form-data; name="gdTitle"

구매 품의서
--WebAppBoundary
Content-Disposition: form-data; name="gdContent"

볼펜 구매
개당 가격 : 2000
수량 : 4
합계 : 8000원
--WebAppBoundary
Content-Disposition: form-data; name="offApplyTitle"

휴가신청서
--WebAppBoundary
Content-Disposition: form-data; name="offStart"

2024-03-01
--WebAppBoundary
Content-Disposition: form-data; name="offEnd"

2024-03-04
--WebAppBoundary
Content-Disposition: form-data; name="offDay"

4
--WebAppBoundary
Content-Disposition: form-data; name="offReason"

연차
--WebAppBoundary
Content-Disposition: form-data; name="offState"

대기
--WebAppBoundary

### 대리결재 위임
POST http://localhost:8031/approval/insertProxy
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3NzU0Nzk3ODgwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc3NzI3OTcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.DRxsWVBXPxZ3PpPZDejkIiJoDkrVn_JopegptuAqrNY

{
  "changeUser": {
    "userCode": 2
  },
  "startDate": "2024-02-13",
  "finishDate": "2024-02-17"
}

### 문서 댓글 작성
POST http://localhost:8031/approval/approvalComment/71
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODEzNzg5ODUxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4MzE3ODksInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.QNZjjJs5fIaSt5LBGM3sctkMBcgMZzjlBdraS28YuEE

{
  "acContent": "수정이 필요할 듯 하여 반려 하였습니다. 수정 후 재기안하세요~"
}

### 재기안
POST http://localhost:8031/approval/reDraft/77
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3ODEzMDczMjgwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4MzEwNzMsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.2digOidmD8x0mFqFhPdpu3G8kvRS4aOXiASK2y-EVUQ

--WebAppBoundary
Content-Disposition: form-data; name="btPhone"

01022222222
--WebAppBoundary
Content-Disposition: form-data; name="btStart"

2024-02-15
--WebAppBoundary
Content-Disposition: form-data; name="btFinish"

2024-02-18
--WebAppBoundary
Content-Disposition: form-data; name="btPlace"

강원도 삼척시 삼척동
--WebAppBoundary
Content-Disposition: form-data; name="btContent"

수리
--WebAppBoundary
Content-Disposition: form-data; name="btTitle"

출장신청서
--WebAppBoundary
Content-Disposition: form-data; name="rfUser"

2,3
--WebAppBoundary
Content-Disposition: form-data; name="lineUser"

21,22,19
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="3333.png"

< ./3333.png
--WebAppBoundary--
Content-Disposition: form-data; name="btPhone"

01022222222
--WebAppBoundary
Content-Disposition: form-data; name="btStart"

2024-02-15
--WebAppBoundary
Content-Disposition: form-data; name="btFinish"

2024-02-18
--WebAppBoundary
Content-Disposition: form-data; name="btPlace"

강원도 삼척시 삼척동
--WebAppBoundary
Content-Disposition: form-data; name="btContent"

수리
--WebAppBoundary
Content-Disposition: form-data; name="btTitle"

출장신청서
--WebAppBoundary
Content-Disposition: form-data; name="eduTitle"

교육기안 신청서
--WebAppBoundary
Content-Disposition: form-data; name="eduName"

장재영
--WebAppBoundary
Content-Disposition: form-data; name="eduStart"

2024-06-01
--WebAppBoundary
Content-Disposition: form-data; name="eduFinish"

2024-12-01
--WebAppBoundary
Content-Disposition: form-data; name="eduInstitution"

장재영 사람 만들기 교육기관
--WebAppBoundary
Content-Disposition: form-data; name="eduPrice"

75000000
--WebAppBoundary
Content-Disposition: form-data; name="eduContent"

사람이 되기 위해 교육을 받고 싶습니다.
--WebAppBoundary
Content-Disposition: form-data; name="gdTitle"

구매 품의서
--WebAppBoundary
Content-Disposition: form-data; name="gdContent"

볼펜 구매
개당 가격 : 2000
수량 : 4
합계 : 8000원
--WebAppBoundary
Content-Disposition: form-data; name="offApplyTitle"

휴가신청서
--WebAppBoundary
Content-Disposition: form-data; name="offStart"

2024-03-01
--WebAppBoundary
Content-Disposition: form-data; name="offEnd"

2024-03-04
--WebAppBoundary
Content-Disposition: form-data; name="offDay"

4
--WebAppBoundary
Content-Disposition: form-data; name="offReason"

연차
--WebAppBoundary


### 문서 공유하기 문서 번호 , 유저코드
POST http://localhost:8031/approval/insertSharedDocument/77/3
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3ODIzMDUzNDIyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDc4NDEwNTMsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.8QNmRFBfTc7U-3WWJooBdPNpXKJrgc0Jie4Tq-B8YwA

### 공유 받은 문서 조회
GET http://localhost:8031/approval/selectSharedDocument
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3OTYxNTg2NDY4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDMiLCJ1c2VyUmFuayI6IuydtOyCrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAzIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjozLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fV0sImV4cCI6MTcwNzk3OTU4NiwidXNlcklkIjoiMjAwMzAyMDAzIiwidXNlckNvZGUiOjMsImVtYWlsIjoiYXNkQGdtYWlsLmNvbSJ9.S-DI4YbPUOYG4i0O8JtnzA4XtJw_N-yJoMWFkF3d-Ec


### 유저 정보 조회
GET http://localhost:8031/approval/user
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4NDI5MjMyMzU3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDMiLCJ1c2VyUmFuayI6IuydtOyCrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAzIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjozLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fV0sImV4cCI6MTcwODQ0NzIzMiwidXNlcklkIjoiMjAwMzAyMDAzIiwidXNlckNvZGUiOjMsImVtYWlsIjoiYXNkQGdtYWlsLmNvbSJ9.0K-VrkwKyJOGh1NIK7lQI6ARz_a332ks54GZ1FqmfpA

### 유저 정보 조회 사용안함
GET http://localhost:8031/approval/findUserDetail/1
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4MzA4Nzk4Mzk5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDMiLCJ1c2VyUmFuayI6IuydtOyCrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAzIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjozLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fV0sImV4cCI6MTcwODMyNjc5OCwidXNlcklkIjoiMjAwMzAyMDAzIiwidXNlckNvZGUiOjMsImVtYWlsIjoiYXNkQGdtYWlsLmNvbSJ9.5whNpUyfRfslqQTTIp7NKaObN6qz3ej0DLmkZhB25YQ
