//-------------------------------** 캘린더 **-----------------------------------------



###캘린더 전체 목록 조회
GET http://localhost:8031/calendar/calendars
Accept: */*
Content-Type: application/json

###캘린더코드로 캘린더 조회
GET http://localhost:8031/calendar/calendar/1
Accept: */*
Content-Type: application/json

###유저코드로 캘린더 조회
GET http://localhost:8031/calendar/calendarsByUserCode/1
Accept: */*
Content-Type: application/json


###로그인 한 유저의 캘린더 조회
GET http://localhost:8031/calendar/calendarsForLoggedInUser
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MTU1MjEzNDgwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDcxNTcwMTMsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.hmTBN7ffSup08XgL3VqZkzez3eL7MSKp7sgK-7vzkIM

### 캘린더 추가
POST http://localhost:8031/calendar/addCalendar
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MTg5NDA0MDQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDcyMDc0MDQsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.LlejeiGn13Q1iPvlYUgVy3OUynkIviTR5JTtDqCnyxc

{
  "calType": "공유 캘린더",
  "calColor": "retfgfddd",
  "calName": "여러개 코드 들어와야함",
  "userCodes": [1,2,19,21]

}

### 캘린더 수정
PATCH http://localhost:8031/calendar/updateCalendar/18
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MTg5NDA0MDQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDcyMDc0MDQsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.LlejeiGn13Q1iPvlYUgVy3OUynkIviTR5JTtDqCnyxc

{
  "calName": " 로그인한 유저가 유저코드 여러명 이름 수정 궈궈",
  "userCodes": [1,3,19,21]
}

### 캘린더 삭제

DELETE http://localhost:8031/calendar/deleteCalendar/17
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MTg4NjY3MTI5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDcyMDY2NjcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.KWI9Bh9-TW-sk114yVrgpzcK6qVQRpdBrYPV84g7xI8


### 캘린더코드로 일정 조회
GET http://localhost:8031/calendar/schedule/1
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA3MTIwOTYwMjUwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoi6rmA7J247IKsIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDcxMjI3NjAsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.fCiJJfPTVJJFilmsTmA0hC9qKJJArAPm8kqbGDY1NDs



### 일정 추가


### 일정 수정
### 일정 삭제

### 회원코드로 일정 전체 조회




###캘린더 타입(공유/개인)으로 조회
GET http://localhost:8031/calendar/calendarByType/공유캘린더
Accept: */*
Content-Type: application/json