### 쪽지 보내기
POST http://localhost:8031/note/send-message
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA5MDExMjE3NjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ0ZWFtRFRPIjp7InRlYW1Db2RlIjoxLCJkZXB0Ijp7ImRlcHRDb2RlIjoxLCJkZXB0TmFtZSI6Iuq0gOumrOuzuOu2gCJ9LCJ0ZWFtTmFtZSI6IuyduOyCrO2MgCJ9LCJ1c2VyUHciOiIkMmEkMTAkcUF0d0hua1UuelNGNmw5UXRGeFd0TzhDT3hzNEpiYW5adFhHSkp2c0pCcklZYTVOdzdNeGUiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoi6rmA7J247IKsIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDkwMjkyMTcsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.1KInxkFraauBRRVZdIvF7dc_VJgQ91zQgJfrYrCEikw

{
  "noteTitle": "쪽지제목",
  "noteContent": "쪽지내용",
  "sendUserCode": 1
}