

###프로젝트 전체목록 조회

GET http://localhost:8031/project/projects
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4MzI0NzEwNDQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoiMjAwMzAyMDAxIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDgzNDI3MTAsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.iI5ZNrR5Z-lY3IE1QgxGZ93GHrY8GTyfkJS8giaW1IY

###프로젝트 하나 조회

GET http://localhost:8031/project/3
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA5MDAwMzY2NDI4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ0ZWFtRFRPIjp7InRlYW1Db2RlIjoxLCJkZXB0Ijp7ImRlcHRDb2RlIjoxLCJkZXB0TmFtZSI6Iuq0gOumrOuzuOu2gCJ9LCJ0ZWFtTmFtZSI6IuyduOyCrO2MgCJ9LCJ1c2VyUHciOiIkMmEkMTAkcUF0d0hua1UuelNGNmw5UXRGeFd0TzhDT3hzNEpiYW5adFhHSkp2c0pCcklZYTVOdzdNeGUiLCJ1c2VyUmFuayI6IuuMgOumrCIsInByb2ZpbGVQYXRoIjoiODUwMjIyMzhlNDkyNDk3Yzk4MGRlNzk0MmZmOWZjMDEucG5nIiwidXNlck5hbWUiOiLquYDsnbjsgqwiLCJ1c2VyUm9sZSI6W3sidXNlckNvZGUiOjEsImF1dGhDb2RlIjoxLCJhdXRob3JpdHkiOnsiYXV0aENvZGUiOjEsImF1dGhOYW1lIjoiUk9MRV9VU0VSIn19LHsidXNlckNvZGUiOjEsImF1dGhDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aENvZGUiOjIsImF1dGhOYW1lIjoiUk9MRV9BRE1JTiJ9fV0sImV4cCI6MTcwOTAxODM2NiwidXNlcklkIjoiMjAwMzAyMDAxIiwidXNlckNvZGUiOjEsImVtYWlsIjoiaHJtQGdtYWlsLmNvbSJ9.C_T-kccZ9MLGNcTBuzm_TD6zTdJ0qimhi9p9HRQGfIE



###프로젝트의 task 조회

GET http://localhost:8031/project/1/tasks
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4OTE1ODk0MDU0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ0ZWFtRFRPIjp7InRlYW1Db2RlIjoxLCJkZXB0Ijp7ImRlcHRDb2RlIjoxLCJkZXB0TmFtZSI6Iuq0gOumrOuzuOu2gCJ9LCJ0ZWFtTmFtZSI6IuyduOyCrO2MgCJ9LCJ1c2VyUHciOiIkMmEkMTAkcUF0d0hua1UuelNGNmw5UXRGeFd0TzhDT3hzNEpiYW5adFhHSkp2c0pCcklZYTVOdzdNeGUiLCJ1c2VyUmFuayI6IuuMgOumrCIsInByb2ZpbGVQYXRoIjoiZWQyYjUxNDA1ZDBkNGYzOTkxYTViZmRiNzJmYmUyOGIucG5nIiwidXNlck5hbWUiOiLquYDsnbjsgqwiLCJ1c2VyUm9sZSI6W3sidXNlckNvZGUiOjEsImF1dGhDb2RlIjoxLCJhdXRob3JpdHkiOnsiYXV0aENvZGUiOjEsImF1dGhOYW1lIjoiUk9MRV9VU0VSIn19LHsidXNlckNvZGUiOjEsImF1dGhDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aENvZGUiOjIsImF1dGhOYW1lIjoiUk9MRV9BRE1JTiJ9fV0sImV4cCI6MTcwODkzMzg5NCwidXNlcklkIjoiMjAwMzAyMDAxIiwidXNlckNvZGUiOjEsImVtYWlsIjoiaHJtQGdtYWlsLmNvbSJ9.gV5L2Ln7ew-ORbQ_TdlrA2XX-hNBMAqT13lMZsqnnT0

###프로젝트의 task 삭제

DELETE http://localhost:8031/project/delete/tasks/1
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4OTgxODg4NjY1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ0ZWFtRFRPIjp7InRlYW1Db2RlIjoxLCJkZXB0Ijp7ImRlcHRDb2RlIjoxLCJkZXB0TmFtZSI6Iuq0gOumrOuzuOu2gCJ9LCJ0ZWFtTmFtZSI6IuyduOyCrO2MgCJ9LCJ1c2VyUHciOiIkMmEkMTAkcUF0d0hua1UuelNGNmw5UXRGeFd0TzhDT3hzNEpiYW5adFhHSkp2c0pCcklZYTVOdzdNeGUiLCJ1c2VyUmFuayI6IuuMgOumrCIsInByb2ZpbGVQYXRoIjoiODUwMjIyMzhlNDkyNDk3Yzk4MGRlNzk0MmZmOWZjMDEucG5nIiwidXNlck5hbWUiOiLquYDsnbjsgqwiLCJ1c2VyUm9sZSI6W3sidXNlckNvZGUiOjEsImF1dGhDb2RlIjoxLCJhdXRob3JpdHkiOnsiYXV0aENvZGUiOjEsImF1dGhOYW1lIjoiUk9MRV9VU0VSIn19LHsidXNlckNvZGUiOjEsImF1dGhDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aENvZGUiOjIsImF1dGhOYW1lIjoiUk9MRV9BRE1JTiJ9fV0sImV4cCI6MTcwODk5OTg4OCwidXNlcklkIjoiMjAwMzAyMDAxIiwidXNlckNvZGUiOjEsImVtYWlsIjoiaHJtQGdtYWlsLmNvbSJ9.NbAMiCtbSu3QYxE3BjsOI-SI5Afbb1GaI6rQ3NFPCvc



###프로젝트 삭제

DELETE http://localhost:8031/project/delete/7
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA4OTgxODg4NjY1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ0ZWFtRFRPIjp7InRlYW1Db2RlIjoxLCJkZXB0Ijp7ImRlcHRDb2RlIjoxLCJkZXB0TmFtZSI6Iuq0gOumrOuzuOu2gCJ9LCJ0ZWFtTmFtZSI6IuyduOyCrO2MgCJ9LCJ1c2VyUHciOiIkMmEkMTAkcUF0d0hua1UuelNGNmw5UXRGeFd0TzhDT3hzNEpiYW5adFhHSkp2c0pCcklZYTVOdzdNeGUiLCJ1c2VyUmFuayI6IuuMgOumrCIsInByb2ZpbGVQYXRoIjoiODUwMjIyMzhlNDkyNDk3Yzk4MGRlNzk0MmZmOWZjMDEucG5nIiwidXNlck5hbWUiOiLquYDsnbjsgqwiLCJ1c2VyUm9sZSI6W3sidXNlckNvZGUiOjEsImF1dGhDb2RlIjoxLCJhdXRob3JpdHkiOnsiYXV0aENvZGUiOjEsImF1dGhOYW1lIjoiUk9MRV9VU0VSIn19LHsidXNlckNvZGUiOjEsImF1dGhDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aENvZGUiOjIsImF1dGhOYW1lIjoiUk9MRV9BRE1JTiJ9fV0sImV4cCI6MTcwODk5OTg4OCwidXNlcklkIjoiMjAwMzAyMDAxIiwidXNlckNvZGUiOjEsImVtYWlsIjoiaHJtQGdtYWlsLmNvbSJ9.NbAMiCtbSu3QYxE3BjsOI-SI5Afbb1GaI6rQ3NFPCvc


###프로젝트 추가
POST http://localhost:8031/project/addProject
Accept: */*
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzA5MDAwMzY2NDI4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ0ZWFtRFRPIjp7InRlYW1Db2RlIjoxLCJkZXB0Ijp7ImRlcHRDb2RlIjoxLCJkZXB0TmFtZSI6Iuq0gOumrOuzuOu2gCJ9LCJ0ZWFtTmFtZSI6IuyduOyCrO2MgCJ9LCJ1c2VyUHciOiIkMmEkMTAkcUF0d0hua1UuelNGNmw5UXRGeFd0TzhDT3hzNEpiYW5adFhHSkp2c0pCcklZYTVOdzdNeGUiLCJ1c2VyUmFuayI6IuuMgOumrCIsInByb2ZpbGVQYXRoIjoiODUwMjIyMzhlNDkyNDk3Yzk4MGRlNzk0MmZmOWZjMDEucG5nIiwidXNlck5hbWUiOiLquYDsnbjsgqwiLCJ1c2VyUm9sZSI6W3sidXNlckNvZGUiOjEsImF1dGhDb2RlIjoxLCJhdXRob3JpdHkiOnsiYXV0aENvZGUiOjEsImF1dGhOYW1lIjoiUk9MRV9VU0VSIn19LHsidXNlckNvZGUiOjEsImF1dGhDb2RlIjoyLCJhdXRob3JpdHkiOnsiYXV0aENvZGUiOjIsImF1dGhOYW1lIjoiUk9MRV9BRE1JTiJ9fV0sImV4cCI6MTcwOTAxODM2NiwidXNlcklkIjoiMjAwMzAyMDAxIiwidXNlckNvZGUiOjEsImVtYWlsIjoiaHJtQGdtYWlsLmNvbSJ9.C_T-kccZ9MLGNcTBuzm_TD6zTdJ0qimhi9p9HRQGfIE

{
  "proTitle": "다시다시",
  "proStartDate": "2024-03-08",
  "proEndDate": "2024-12-31",
  "proContent": "이 프로젝트는 새로운 서비스 개발을 목표로 합니다.",
  "userCodes": [1,2,3]

}
