### 로그인
POST http://localhost:8031/auth/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "userId": "200302003",
  "userPw": "1234"
}

### 내 정보 조회
GET http://localhost:8031/users/user/200302001
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA2OTI0OTAwMTM5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyTmFtZSI6IjIwMDMwMjAwMSIsInVzZXJSb2xlIjpbeyJ1c2VyQ29kZSI6MSwiYXV0aENvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRoQ29kZSI6MSwiYXV0aE5hbWUiOiJST0xFX1VTRVIifX0seyJ1c2VyQ29kZSI6MSwiYXV0aENvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRoQ29kZSI6MiwiYXV0aE5hbWUiOiJST0xFX0FETUlOIn19XSwiZXhwIjoxNzA2OTI2NzAwLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.GEV2CBD3cXZWTD8DP7SfOOetMuEioyp7Ip-g-hGVDQQ

### 직원 등록(회원가입)
POST http://localhost:8031/auth/signup
Content-Type: application/json
Accept: */*

{
  "userName": "차과장",
  "userPw": "1111",
  "userRank": "과장",
  "email": "gwagwa@gmail.com",
  "phone": "010-1111-1811",
  "entDate": "2024-02-06",
  "teamCode": "2"
}

### 직원 전체 조회
GET http://localhost:8031/users/users-management
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA2OTI3NzMwNTgzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyTmFtZSI6IjIwMDMwMjAwMSIsInVzZXJSb2xlIjpbeyJ1c2VyQ29kZSI6MSwiYXV0aENvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRoQ29kZSI6MSwiYXV0aE5hbWUiOiJST0xFX1VTRVIifX0seyJ1c2VyQ29kZSI6MSwiYXV0aENvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRoQ29kZSI6MiwiYXV0aE5hbWUiOiJST0xFX0FETUlOIn19XSwiZXhwIjoxNzA2OTI5NTMwLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.SE9qkQaiKaC-OsBGj89KpLTBavJlZ5KXC8LW6uadSCw

### 직원 개별 조회
GET http://localhost:8031/users/users-management/1
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA2OTMwMDI3MTM2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyTmFtZSI6IjIwMDMwMjAwMSIsInVzZXJSb2xlIjpbeyJ1c2VyQ29kZSI6MSwiYXV0aENvZGUiOjEsImF1dGhvcml0eSI6eyJhdXRoQ29kZSI6MSwiYXV0aE5hbWUiOiJST0xFX1VTRVIifX0seyJ1c2VyQ29kZSI6MSwiYXV0aENvZGUiOjIsImF1dGhvcml0eSI6eyJhdXRoQ29kZSI6MiwiYXV0aE5hbWUiOiJST0xFX0FETUlOIn19XSwiZXhwIjoxNzA2OTMxODI3LCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.5EctueEyzGqpCndYZlWrrTMGyzwUObdGiKtmXzSpZj0

### 직원 정보 수정
PUT http://localhost:8031/users/user-update
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJkYXRlIjoxNzA3MTIwMjU1MzIyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMDAzMDIwMDEiLCJ1c2VyUmFuayI6IuuMgOumrCIsInVzZXJOYW1lIjoi6rmA7J247IKsIiwidXNlclJvbGUiOlt7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MSwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoxLCJhdXRoTmFtZSI6IlJPTEVfVVNFUiJ9fSx7InVzZXJDb2RlIjoxLCJhdXRoQ29kZSI6MiwiYXV0aG9yaXR5Ijp7ImF1dGhDb2RlIjoyLCJhdXRoTmFtZSI6IlJPTEVfQURNSU4ifX1dLCJleHAiOjE3MDcxMzgyNTUsInVzZXJJZCI6IjIwMDMwMjAwMSIsInVzZXJDb2RlIjoxLCJlbWFpbCI6ImhybUBnbWFpbC5jb20ifQ.F69syzx6hG-f7OKpFz1CtTGX8PXTTbr2tnZFCtyEwHY

{
  "userCode": "22",
  "userId": "240203003",
  "userName": "김사원사원",
  "userRank": "사원",
  "email": "sawon@gmail.com",
  "phone": "010-8888-3333",
  "entDate": "2024-02-03",
  "teamCode": "2",
  "resignDate": "9999-12-31",
  "userRole": [
    {
      "userCode": 1,
      "authCode": 2,
      "authority": {
        "authCode": 2,
        "authName": "ROLE_ADMIN"
      }
    }
  ]
}